### ISSUE TITLE
Your example with pure JavaScript question

### ISSUE THREAD

**Issue by MikeSuiter** [floydjones1/monorepo-cra#1]
@floydjones1 I watched your video and read your article which was great! I cloned your repo and did a `yarn start`, then introduced an error to Button.tsx, and got Failed to compile errors in both the terminal and browser like I should.

I'm using CRACO exactly like your example except I'm using pure JavaScript and have a problem when there's an error, the browser will display like "ReferenceError: Can't find variable: DummyCmp" but the terminal says "Compiled successfully!". If the error is introduced to the app src, then the terminal shows the error like it should. If the error is in a dependent package, then only the browser shows it and terminal say successful. 

When I ran across your example I was excited to see the error in the dependent package show up in the terminal. I compared and copied your CRACO and monorepo configs, and I still can't get the error to show in the terminal. Any idea on why and what I can do to fix it? I think the difference is the Typescript is being compiled differently than the JavaScript. 

I realize this isn't an issue with your repo, but I've been trying to track this down for a while and hope you might have a tip.

Thanks!

**Comment by floydjones1** [comment]
It would be great if I could get an minimum replica repo for the example your are mentioning. My example is a react to react monorepo project.  It sounds like you are doing react to vanilla javascript. 
Is that correct? @MikeSuiter

**Comment by MikeSuiter** [comment]
Hey @floydjones1 thanks for the quick reply and I just pushed my test repo. My example project is all React, it just uses JavaScript instead of Typescript. My layout is very similar to yours except I have `apps` folder for apps and `packages` folder for shared code. Our real-life monorepo currently has 8 apps and 7 packages. Here is the example repo:

https://github.com/MikeSuiter/craco-monorepo-example

Go to the root of the workspace and run `yarn start` and you'll see both the terminal and browser are happy. Now change `PinkButton` to `PinkButton123` in `packages/core/src/components/Layout.js` and the terminal still says successful but the browser does show the error. This is an annoyance for development, but a production build will succeed so that's not good at all. Any errors in `packages` do not cause development or production builds to fail.

Now go to `apps/app-one/src/App.js` and change `LocalButton` to `LocalButton123` and this time both the terminal and browsers have errors, as they should. So there is something causing errors to fail properly in `apps` but not in `packages`. I've been trying to track this down on and off for almost 2 months now with no luck, that's why when I ran across your project and got `packages` to fail I was hopeful. 

Any direction would be greatly appreciated.

**Comment by floydjones1** [comment]
Just FYI I got it to output errors but I'm trying to fix an issue with it not being able to parse .jsx files in other folders.
I think that was always an issue but it never surfaced in the terminal.

Hope to get your example repo working! @MikeSuiter

**Comment by floydjones1** [comment]
@MikeSuiter GOOD NEWS! I got it to work, please change your craco.config.js to the code below. I made some slight modifications:
I think you can guess why this works. Let me know if you have anymore questions :) 


```
const path = require('path');
const { getLoader, loaderByName, ESLINT_MODES } = require('@craco/craco');
const { getPlugin, pluginByName } = require('@craco/craco/lib/webpack-plugins');

const packages = ['btns', 'core'];
const absolutePaths = [];
packages.forEach((item) => {
  absolutePaths.push(path.join(__dirname, `packages/${item}/src`));
});
module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      const { isFound, match } = getLoader(webpackConfig, loaderByName('babel-loader'));
      if (isFound) {
        const include = Array.isArray(match.loader.include) ? match.loader.include : [match.loader.include];
        match.loader.include = include.concat(absolutePaths);
        console.log('Loading sources from:', match.loader.include);
      }

      const { match: eslintPlugin } = getPlugin(webpackConfig, pluginByName('ESLintWebpackPlugin'));
      eslintPlugin.options['context'] = path.join(__dirname, 'packages');

      return webpackConfig;
    },
  },
  eslint: {
    enable: true,
    mode: ESLINT_MODES.extends,
  },
};
```

**Comment by MikeSuiter** [comment]
@floydjones1 thanks so much for your help! Funny thing is I my thoughts why it worked with TypeScript was because of the compiling, but it never came to me that ESLint does the "compiling" for JavaScript. After your fix I realized the obvious! 

I did have to make a slight change since the errors weren't showing on the apps folder by doing this.

```
      eslintPlugin.options['context'] = __dirname;
      eslintPlugin.options['files'] = ['apps', 'packages'];
```

**Comment by floydjones1** [comment]
Great! Glad to hear it works now. I'll close this issue if nothing else 😄
